-- select 
-- action_id,	
-- contact_id,	
-- contact_uuid,
-- follow_up_date,	
-- priority,	
-- description,
-- action_uuid,
-- level_uuid
-- from action where level_uuid = $1;
select * from action where level_uuid = $1;